# Generated by Django 5.2 on 2025-11-06 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0008_delete_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (minimum 2 characters)",
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, message="Tag name must be at least 2 characters long"
                            ),
                            django.core.validators.RegexValidator(
                                message="Tag name contains invalid characters",
                                regex="^[a-zA-Z0-9\\s\\-\\_áéíóúñÁÉÍÓÚÑ]+$",
                            ),
                        ],
                    ),
                ),
                ("posts", models.ManyToManyField(related_name="tags", to="blog.post")),
            ],
        ),
    ]
