# Generated by Django 5.2 on 2025-11-07 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Tag name (minimum 2 characters)",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Tag name must be at least 2 characters long"
                    ),
                    django.core.validators.RegexValidator(
                        message="Tag name contains invalid characters",
                        regex="^[a-zA-Z0-9\\s\\-\\_áéíóúñÁÉÍÓÚÑ]+$",
                    ),
                ],
            ),
        ),
    ]
