# Generated by Django 5.2 on 2025-10-23 11:18

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.RemoveField(
            model_name="post",
            name="excerpt",
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(related_name="tags", to="blog.post"),
        ),
    ]
