# Generated by Django 5.2 on 2025-11-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blog_title_alter_post_title_alter_tag_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
