# Generated by Django 5.2 on 2025-11-07 11:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_delete_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(
                help_text="Blog title (minimum 5 characters)",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, message="Blog title must be at least 5 characters long"
                    ),
                    django.core.validators.RegexValidator(
                        message="Blog title contains invalid characters",
                        regex="^[a-zA-Z0-9\\s\\-\\_áéíóúñÁÉÍÓÚÑ]+$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
