# Generated by Django 5.2 on 2025-10-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSServer', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='description',
        ),
    ]
